# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Bump patch version before checkout
      run: npm version patch
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Cache node modules
      uses: actions/cache@v1.1.2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: Install Dependencies
      run: npm install
      
  # Publish storybook on gh-pages
  publish-storybook:
    name: Publish Storybook on GH Pages
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: npm run deploy-storybook
        
  # Publish npm
  publish-npm:
    name: Publish lib on npm
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Build lib
        run: npm run build
      
      - name: Publish on npm
        run: npm publish
